package com.valorantagentsapplicationcleanarchitecture.domain.use_case

import com.valorantagentsapplicationcleanarchitecture.domain.repository.ValorantAgentsRepository

class ValorantAgentsUseCase(valorantAgentsRepository: ValorantAgentsRepository) {
}